version: '3.7'

services:

  postgres:
    image: postgres:13
    platform: linux/arm64
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    platform: linux/arm64
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: dilnaz2510
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
    volumes:
      - ./data:/data
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    platform: linux/arm64
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: sup3rs3cret
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
    entrypoint: >
      bash -c "
        airflow db upgrade &&
        airflow users create --username admin --firstname Dilnaz --lastname Saparbek --role Admin --email dilnazsaparbek@gmail.com --password 'dilnaz2510'
      "

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    platform: linux/arm64
    depends_on:
      - airflow-init
    command: scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: sup3rs3cret
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/data

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    platform: linux/arm64
    depends_on:
      - airflow-init
    command: webserver
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: sup3rs3cret
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/data

  superset:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    depends_on:
      - postgres
      - clickhouse
    environment:
      SUPERSET_SECRET_KEY: 'sup3rs3cret'
    ports:
      - "8088:8088"
    volumes:
      - superset_home:/app/superset_home
    command: >
      bash -c "
        superset db upgrade &&
        superset fab create-admin --username admin --firstname Dilnaz --lastname Saparbek --email dilnazsaparbek@gmail.com --password dilnaz2510 &&
        superset init &&
        superset run -h 0.0.0.0 -p 8088
      "

volumes:
  postgres_data:
  superset_home:
